export { createIssue, resetIssueCounter } from './createIssue.js'
export { createDomBloatDetector } from './domBloat.js'
export { createDuplicateRequestsDetector } from './duplicateRequests.js'
export { createConsoleSpamDetector } from './consoleSpam.js'
export { createMemoryLeakDetector } from './memoryLeak.js'
export { createLayoutThrashingDetector } from './layoutThrashing.js'
export { createUnoptimizedImagesDetector } from './unoptimizedImages.js'
export { createLongTaskAttributionDetector } from './longTaskAttribution.js'
export { createResourceBloatDetector } from './resourceBloat.js'
