import {
  ALL_PROBLEMS,
  CATEGORY_META,
  getCategoryMeta,
  getFrameworkParams,
  getProblem,
  isCategory,
} from '@/lib/problems'
import type { Framework } from '@/lib/problems/types'
import {
  categoryToMarkdown,
  fixHubToMarkdown,
  problemToMarkdown,
} from '@/lib/problems/markdown'
import { absoluteUrl } from '@/lib/site'
import { allDocsUrls, docsPageToMarkdown } from './docs'
import { landingMarkdown } from './landing'

// ── Markdown path router ─────────────────────────────────────────────────────
// Maps the segments of a `/md/...` request to the right markdown generator. The
// middleware rewrites `<path>.md` and `Accept: text/markdown` requests here; the
// route handler (app/md/[[...path]]/route.ts) prerenders every known path.

export const resolveMarkdownForPath = (segments: readonly string[]): string | null => {
  if (segments.length === 0) return landingMarkdown()

  const [a, b, c] = segments

  if (segments.length === 1) {
    if (a === 'home') return landingMarkdown()
    if (a === 'fix') return fixHubToMarkdown()
    if (a === 'docs') return docsPageToMarkdown('/docs')
    return null
  }

  if (a === 'fix') {
    if (segments.length === 2) {
      if (isCategory(b)) return categoryToMarkdown(getCategoryMeta(b))
      const problem = getProblem(b)
      return problem ? problemToMarkdown(problem) : null
    }
    if (segments.length === 3) {
      const problem = getProblem(b)
      if (problem && problem.frameworkFixes?.[c as Framework]) {
        return problemToMarkdown(problem, c as Framework)
      }
      return null
    }
  }

  if (a === 'docs') return docsPageToMarkdown(`/${segments.join('/')}`)

  return null
}

// Every markdown path to prerender — landing (served at `/md/home`), the fix hub
// + categories + problems + framework variants, and every docs page. The landing
// uses a plain `home` segment because Next normalises a literal `index` segment
// away and won't reliably prerender the optional catch-all's empty root.
export const markdownPaths = (): { path: string[] }[] => {
  const paths: string[][] = [['home'], ['fix']]
  for (const c of CATEGORY_META) paths.push(['fix', c.key])
  for (const p of ALL_PROBLEMS) paths.push(['fix', p.slug])
  for (const v of getFrameworkParams()) paths.push(['fix', v.slug, v.framework])
  for (const url of allDocsUrls()) paths.push(url.replace(/^\//, '').split('/'))
  return paths.map((path) => ({ path }))
}

// The whole site concatenated into one markdown document for /llms-full.txt, so
// an LLM can ingest every doc and every fix guide in a single fetch.
export const renderLlmsFull = (): string => {
  const sections: string[] = [landingMarkdown()]

  sections.push('# Documentation')
  for (const url of allDocsUrls()) {
    const md = docsPageToMarkdown(url)
    if (md) sections.push(md)
  }

  sections.push('# Fix guides')
  for (const problem of ALL_PROBLEMS) sections.push(problemToMarkdown(problem))

  sections.push(`---\n\nGenerated by VibeCheck — ${absoluteUrl('/llms.txt')}`)
  return sections.join('\n\n---\n\n') + '\n'
}
