import { docs } from 'collections/server'
import { loader } from 'fumadocs-core/source'

// Content source adapter. `docs` is generated by fumadocs-mdx into `.source`
// (see the `collections/*` path alias in tsconfig); `loader()` turns it into
// the page tree + page lookup API the docs layout and pages consume.
export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
})
